version: "3"

services:
  db:
    image: mysql:5.6
    platform: linux/amd64
    environment:
      MYSQL_DATABASE: asunaro
      MYSQL_USER: asunaro
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_volume:/var/lib/mysql:cached
      - ./db/conf.d:/etc/mysql/conf.d
  migrate:
    build: ./db/migrations
    depends_on:
      - db
    command: ["up"]
    environment:
      WAIT_HOSTS: db:3306
      MIGRATIONS_DIR: /migrations
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: asunaro
      MYSQL_USER: asunaro
      MYSQL_PASSWORD: password
    volumes:
      - ./db/migrations/migrations:/migrations
volumes:
  db_volume:
    driver: local
