version: "3"

services:
  db:
    image: mysql:8.3
    platform: linux/amd64
    environment:
      MYSQL_DATABASE: cms 
      MYSQL_USER: asunaro
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - db_volume:/var/lib/mysql:cached
      - ./db/conf.d:/etc/mysql/conf.d
  migrate:
    build: ./db/migrations
    depends_on:
      - db
    command: ["up"]
    environment:
      WAIT_HOSTS: db:3306
      MIGRATIONS_DIR: /migrations
      MYSQL_HOST: db
      MYSQL_PORT: 3306
      MYSQL_DATABASE: cms
      MYSQL_USER: asunaro
      MYSQL_PASSWORD: password
    volumes:
      - ./db/migrations/migrations:/migrations
  tbls:
    image: ghcr.io/k1low/tbls
    working_dir: /db
    volumes: 
    - ./db/:/db
    depends_on:
      - migrate
    entrypoint: > 
      tbls doc mysql://asunaro:password@db:3306/cms

volumes:
  db_volume:
    driver: local
