CREATE DATABASE IF NOT EXISTS cms;
CREATE TABLE IF NOT EXISTS cms.contents(
-- `id` BINARY(16) NOT NULL PRIMARY KEY DEFAULT (UUID_TO_BIN(UUID())) COMMENT 'コンテンツID',
`id` char(36) NOT NULL PRIMARY KEY DEFAULT (UUID()) COMMENT 'コンテンツID',
`title` varchar(255) NOT NULL,
`body` text NOT NULL,
`created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
`updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) COMMENT 'コンテントテーブル' ENGINE=InnoDB DEFAULT CHARSET=utf8;
